#!/usr/bin/env bash

shopt -s nullglob

[ -z "$ROOT_DIR" ] && ROOT_DIR="$HOME/jb"
[ -z "$SONG_DIR" ] && SONG_DIR="$ROOT_DIR/songs"
[ -z "$INFO_DIR" ] && INFO_DIR="$ROOT_DIR/cache"
[ -z "$PLAYER" ] && PLAYER="afplay"
[ -z "$FILTER" ] && FILTER="fzf"
[ -z "$MULTI_FILTER" ] && MULTI_FILTER="fzf -m"
