#!/usr/bin/env bash

shopt -s nullglob

[ -z "$ROOT_DIR" ] && ROOT_DIR="$HOME/jb"
[ -z "$SONG_DIR" ] && SONG_DIR="$ROOT_DIR/songs"
[ -z "$INFO_DIR" ] && INFO_DIR="$ROOT_DIR/cache"
[ -z "$PLAYER" ] && PLAYER="afplay"
[ -z "$FILTER" ] && FILTER="fzf"
[ -z "$MULTI_FILTER" ] && MULTI_FILTER="fzf -m"


# repeats action for each line of input
repeat_action() {
  action="$1"
  while read -r line; do
    echo "$line" | $action
  done < /dev/stdin
}

# song ID -> adds song
add_song() {
  read -r song_id
  dest="${SONG_DIR}/%(id)s.%(ext)s"
  youtube-dl --no-playlist -f 'bestaudio[ext=m4a]' --write-info-json -o "$dest" "$song_id"
}

# song ID -> deletes song
del_song() {
  read -r song_id
  [ -n "$id" ] || exit 1;
  rm -v "$SONG_DIR"/"$song_id"*
}

# song ID -> plays song
play_song() {
  read -r song_id
  $PLAYER "$SONG_DIR"/"$song_id".m4a
}

# song ID -> description/metadata
describe_song() {
  read -r song_id
  cached_info="$INFO_DIR"/"$song_id"
  [ -e "$cached_info" ] || {
    # NOTE: cache the info
    info_file="$SONG_DIR"/"$song_id".info.json
    [ -d "$INFO_DIR" ] || mkdir -p "$INFO_DIR"
    title=$(jq -r '.title' < "$info_file")
    uploader=$(jq -r '.uploader' < "$info_file")
    printf "%s uploaded by %s [id:%s]\n" "$title" "$uploader" "$song_id" > "$cached_info"
  }
  cat "$cached_info"
}

# description/metadata -> song ID
get_song_id() {
  read -r song_id
  echo "$song_id" \
    | grep -E '\[id:[A-Za-z0-9_-]+\]' \
    | sed 's/.*\[id://; s/\]$//'
}

# get a list of song IDs
all_song_ids() {
  for song in "$SONG_DIR"/*.m4a; do
    printf "%s\n" "$(basename "$song" .m4a)"
  done
}

# get user selection, returns song ID(s)
# option of single or multiple selection
select_song() {
  case "$1" in
    single) filter=$FILTER ;;
    multi) filter=$MULTI_FILTER ;;
    *) exit 1 ;;
  esac
  all_song_ids \
    | repeat_action describe_song \
    | $filter \
    | repeat_action get_song_id
}

case "$1" in
  a) repeat_action add_song ;;
  d) repeat_action del_song ;;
  p) repeat_action play_song ;;
  D) repeat_action describe_song ;;
  l) all_song_ids | repeat_action describe_song ;;
  s1) select_song single ;;
  s) select_song multi ;;
  ids) all_song_ids ;;
  *) echo "nope" ;;
esac
